[package]
name = "spdlog-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "spdlog"

[features]
level-off      = []
level-critical = []
level-error    = []
level-warn     = []
level-info     = []
level-debug    = []
level-trace    = []

release-level-off      = []
release-level-critical = []
release-level-error    = []
release-level-warn     = []
release-level-info     = []
release-level-debug    = []
release-level-trace    = []

source-location = []

[dependencies]
chrono = "0.4"
thiserror = "1.0"
atty = "0.2"
if_chain = "1.0"
getset = "0.1"
lazy_static = "1.4"
cfg-if = "1.0"
spin = "0.9"
arc-swap = "1.5"

[dev-dependencies]
crossbeam = "0.8"
clap = { version = "3.0.0-rc.7", features = ["derive"] }

[[bench]]
name = "compare_with_cpp_spdlog"
harness = false
