[package]
name = "spdlog-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "spdlog"

[dependencies]
chrono = "0.4"
thiserror = "1.0"
atty = "0.2"
if_chain = "1.0"
getset = "0.1"
lazy_static = "1.4"
cfg-if = "1.0"

[dev-dependencies]
crossbeam = "0.8"
clap = { version = "3.0.0-rc.7", features = ["derive"] }

[[bench]]
name = "compare_with_cpp_spdlog"
harness = false
