name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # When updating this, also update:
  # - src/lib.rs
  # - Cargo.toml
  # - README.md
  rust_minver: 1.56.0

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install nightly
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v1
    - name: Check formatting
      run: cargo +nightly fmt --all --verbose -- --check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        fn_features: ['', 'log native multi-thread']
        cfg_feature: ['', 'flexible-string', 'source-location']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libsystemd-dev
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v1
    - name: Run tests
      run: cargo test --features "${{ env.fn_features }} ${{ matrix.cfg_feature }}" --verbose

  clippy:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libsystemd-dev
    - name: Install nightly
      run: |
        rustup toolchain install nightly
        rustup component add clippy --toolchain nightly
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v1
    - name: Run clippy 
      run: cargo clippy --all-features --tests --examples -- -D warnings
    - name: Run clippy nightly for benches
      run: cargo +nightly clippy --all-features --benches

  check-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libsystemd-dev
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v1
    - name: Run rustdoc
      run: |
        cd spdlog
        cargo +nightly rustdoc --all-features --verbose -- -D warnings
        cd ../spdlog-macros
        cargo +nightly rustdoc --all-features --verbose -- -D warnings

  check-minver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libsystemd-dev
    - name: Install Rust ${{ env.rust_minver }}
      run: rustup toolchain install ${{ env.rust_minver }}
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v1
    - name: Run check for core with Rust ${{ env.rust_minver }}
      run: cargo +${{ env.rust_minver }} check --all-features --verbose
