name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        features: ['', 'flexible-string']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with default features
      if: matrix.features == ''
      run: cargo test --verbose
    - name: Run tests with specified features
      if: matrix.features != ''
      run: cargo test --features ${{ matrix.features }} --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: |
        rustup toolchain install nightly
        rustup component add clippy --toolchain nightly
    - name: Run clippy
      run: cargo +nightly clippy --tests --benches
